script: |
  if [ ! -d "docker-node-app" ]; then
    git clone https://github.com/pragalearn11/docker-node-app.git
  fi

  cd docker-node-app
  git pull

  docker stop $(docker ps -q) || true
  docker rm $(docker ps -aq) || true

  docker build -t docker-app .
  docker run -d -p 3000:3000 docker-app
